version: 2.1

orbs:
   node: circleci/node@3.0.1

executors:
   node:
      docker:
         - image: cimg/node:lts

jobs:
   publish:
      working_directory: ~/stylx
      executor: node
      steps:
         - checkout
         - node/install:
              install-yarn: true
              node-version: lts
         - run: node --version
         - run: yarn --version
         - node/install-packages:
              app-dir: ~/stylx
              pkg-manager: yarn
         # TODO: Design solution to deal with fucking monorepo.
         - run:
              name: Authenticate with registry
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/stylx/packages/prettier/.npmrc
         - run: cd ~/stylx/packages/prettier && npm publish

workflows:
   publish:
      jobs:
         - publish
