version: 2.1

orbs:
 node: circleci/node@4.0.0

executors:
 node:
  docker:
   - image: cimg/base:2020.01

jobs:
 publish:
  working_directory: ~/archestyle
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - node/install-packages:
      app-dir: ~/archestyle
      pkg-manager: yarn
      override-ci-command: yarn --frozen-lockfile
   - run:
      name: Authenticate with registry
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/archestyle/.npmrc
   - run: yarn run lerna publish from-package -y

workflows:
 publish:
  jobs:
   - publish
