version: 2.1

orbs:
   node: circleci/node@4.0.0

executors:
   node:
      docker:
         - image: cimg/node:lts

jobs:
   publish:
      working_directory: ~/stylx
      executor: node
      steps:
         - checkout
         - node/install:
              install-yarn: true
              node-version: lts
         - run: node --version
         - run: yarn --version
         - node/install-packages:
              app-dir: ~/stylx
              pkg-manager: yarn
         - run:
              name: Authenticate with registry
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/stylx/.npmrc
         - run: yarn release

workflows:
   publish:
      jobs:
         - publish
