version: 2.1

orbs:
 node: circleci/node@4.0.0

executors:
 node:
  docker:
   - image: cimg/base:2020.01

jobs:
 publish:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - run: node --version
   - run: yarn --version
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
   - run:
      name: Authenticate with registry
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/stylx/.npmrc
   - run: yarn release

workflows:
 publish:
  jobs:
   - publish
