version: 2.1

orbs:
   node: circleci/node@3.0.1

executors:
   node:
      docker:
         - image: cimg/node:lts

jobs:
   publish:
      executor: node
      working_directory: ~/avenor
      steps:
         - checkout
         - node/install:
              install-yarn: true
              node-version: lts
         - run: node --version
         - run: yarn --version
         - node/install-packages:
              app-dir: ~/avenor
              pkg-manager: yarn
         - run: lerna bootstrap
         - run:
              name: Authenticate with registry
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
         - run: lerna publish from-package -y -c

workflows:
   tests:
      jobs:
         - publish
